# move vimrc to XDG config directory
export MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" 
export VIMINIT='source $MYVIMRC'

# set tldr config to XDG Base Dir spec
export TLRC_CONFIG="$XDG_CONFIG_HOME/tldr"

# Set the less history file to the XDG state directory
export LESSHISTFILE="$XDG_STATE_HOME/less/.lesshst"
