source "$HOME/.config/zsh/xdg.zsh"
umask 077
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# put zsh state files in XDG state directory
export HISTFILE="$XDG_STATE_HOME/zsh/history"

# ZimFW setup
zstyle ':zim:zmodule' use 'degit'
zstyle ':zim:input' double-dot-expand yes
zstyle ':zim:completion' dumpfile ${XDG_CACHE_HOME}/zsh/zcompdump
zstyle ':completion::complete:*' cache-path ${XDG_CACHE_HOME}/zsh
ZIM_HOME=$XDG_CACHE_HOME/zim
ZIM_CONFIG_FILE=$XDG_CONFIG_HOME/zim/zimrc
## Download zimfw plugin manager if missing.
if [[ ! -e ${ZIM_HOME}/zimfw.zsh ]]; then
  curl -fsSL --create-dirs -o ${ZIM_HOME}/zimfw.zsh \
      https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
fi

## Install missing modules, and update ${ZIM_HOME}/init.zsh if missing or outdated.
if [[ ! ${ZIM_HOME}/init.zsh -nt ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
  source ${ZIM_HOME}/zimfw.zsh init -q
fi
## Initialize modules.
source ${ZIM_HOME}/init.zsh

# move zcompcache to XDG_CACHE_HOME
export ZSH_COMPDUMP="$XDG_CACHE_HOME/zsh/.zcompcache"

source $XDG_CONFIG_HOME/zsh/aliases

export PATH="$HOME/.local/bin:$PATH"

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh
